/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as HatchRouteImport } from './routes/hatch'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetsPetIdRouteImport } from './routes/pets.$petId'

const MarketplaceRoute = MarketplaceRouteImport.update({ id: '/marketplace', path: '/marketplace', getParentRoute: () => rootRouteImport } as any)
const HatchRoute = HatchRouteImport.update({ id: '/hatch', path: '/hatch', getParentRoute: () => rootRouteImport } as any)
const ConnectRoute = ConnectRouteImport.update({ id: '/connect', path: '/connect', getParentRoute: () => rootRouteImport } as any)
const ArenaRoute = ArenaRouteImport.update({ id: '/arena', path: '/arena', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({ id: '/pets/$petId', path: '/pets/$petId', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/connect': typeof ConnectRoute
  '/hatch': typeof HatchRoute
  '/marketplace': typeof MarketplaceRoute
  '/pets/$petId': typeof PetsPetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/connect': typeof ConnectRoute
  '/hatch': typeof HatchRoute
  '/marketplace': typeof MarketplaceRoute
  '/pets/$petId': typeof PetsPetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/connect': typeof ConnectRoute
  '/hatch': typeof HatchRoute
  '/marketplace': typeof MarketplaceRoute
  '/pets/$petId': typeof PetsPetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arena' | '/connect' | '/hatch' | '/marketplace' | '/pets/$petId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arena' | '/connect' | '/hatch' | '/marketplace' | '/pets/$petId'
  id: '__root__' | '/' | '/arena' | '/connect' | '/hatch' | '/marketplace' | '/pets/$petId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  ConnectRoute: typeof ConnectRoute
  HatchRoute: typeof HatchRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PetsPetIdRoute: typeof PetsPetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': { id: '/marketplace'; path: '/marketplace'; fullPath: '/marketplace'; preLoaderRoute: typeof MarketplaceRouteImport; parentRoute: typeof rootRouteImport }
    '/hatch': { id: '/hatch'; path: '/hatch'; fullPath: '/hatch'; preLoaderRoute: typeof HatchRouteImport; parentRoute: typeof rootRouteImport }
    '/connect': { id: '/connect'; path: '/connect'; fullPath: '/connect'; preLoaderRoute: typeof ConnectRouteImport; parentRoute: typeof rootRouteImport }
    '/arena': { id: '/arena'; path: '/arena'; fullPath: '/arena'; preLoaderRoute: typeof ArenaRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/pets/$petId': { id: '/pets/$petId'; path: '/pets/$petId'; fullPath: '/pets/$petId'; preLoaderRoute: typeof PetsPetIdRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  ConnectRoute: ConnectRoute,
  HatchRoute: HatchRoute,
  MarketplaceRoute: MarketplaceRoute,
  PetsPetIdRoute: PetsPetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
